# Generated by Django 4.0.4 on 2022-05-26 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('calling_number', models.PositiveSmallIntegerField(unique_for_date='date')),
                ('status', models.CharField(choices=[('C', 'Received'), ('P', 'Preparing'), ('R', 'Ready'), ('D', 'Delivered')], default='C', max_length=2)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table')),
            ],
        ),
    ]
